[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1-p1"
path = "bin/1/p1.rs"

[[bin]]
name = "1-p2"
path = "bin/1/p2.rs"

[[bin]]
name = "2-p1"
path = "bin/2/p1.rs"

[[bin]]
name = "2-p2"
path = "bin/2/p2.rs"
